// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUurfJsBRPxqKv7iA2Lz7R70pC0VOWyCU',
    appId: '1:340325512080:web:d2bb16ea57d9e2ba04b915',
    messagingSenderId: '340325512080',
    projectId: 'kawaii-589d1',
    authDomain: 'kawaii-589d1.firebaseapp.com',
    storageBucket: 'kawaii-589d1.firebasestorage.app',
    measurementId: 'G-7JGZTS8RC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMfSVWjmbDJkaL4uVsPIxsM7IVElbMRS4',
    appId: '1:340325512080:android:e853cd6aa9c3f22f04b915',
    messagingSenderId: '340325512080',
    projectId: 'kawaii-589d1',
    storageBucket: 'kawaii-589d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmWwQ0m4yvaB4fw7pQWez31Oqzw_TSfRM',
    appId: '1:340325512080:ios:52f9bf0ec02f613f04b915',
    messagingSenderId: '340325512080',
    projectId: 'kawaii-589d1',
    storageBucket: 'kawaii-589d1.firebasestorage.app',
    iosBundleId: 'com.example.kawaiiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmWwQ0m4yvaB4fw7pQWez31Oqzw_TSfRM',
    appId: '1:340325512080:ios:52f9bf0ec02f613f04b915',
    messagingSenderId: '340325512080',
    projectId: 'kawaii-589d1',
    storageBucket: 'kawaii-589d1.firebasestorage.app',
    iosBundleId: 'com.example.kawaiiApp',
  );
}
